Case1/FrontEnd/Minor.Case1.FrontEnd/src/Minor.Case1.FrontEnd.FrontEnd/ViewModels/InschrijvingenViewModel.cs
using Minor.Case1.FrontEnd.FrontEnd.Agents.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minor.Case1.FrontEnd.FrontEnd.ViewModels
{
    public class InschrijvingenViewModel
    {
        public int InstantieId { get; set; }
        public IList<Inschrijving> Inschrijvingen { get; set; }
    }
}

Case1/FrontEnd/Minor.Case1.FrontEnd/src/Minor.Case1.FrontEnd.FrontEnd/Controllers/CursistInschrijvenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Minor.Case1.FrontEnd.FrontEnd.Agents;
using Minor.Case1.FrontEnd.FrontEnd.Agents.Models;

namespace Minor.Case1.FrontEnd.FrontEnd.Controllers
{
    public class CursistInschrijvenController : Controller
    {
        private ICursusInstantieService _agent;

        public CursistInschrijvenController()
        {
            _agent = new CursusInstantieService();
            _agent.BaseUri = new Uri("http://localhost:11380/");
        }
        // GET: CursusInstantie
        [Route("/CAS_YK/CASsite/CursistInschrijven/Index")]
        public ActionResult Index(int id)
        {
            return View(new Inschrijving()
            {
                CursusInstantieId = id,
                CursistId = 0,
            });
        }

        // POST: CursistInschrijven/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/CAS_YK/CASsite/CursistInschrijven/Create")]
        public ActionResult Create(Inschrijving inschrijving)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _agent.PostInschrijving(inschrijving);
                    return RedirectToAction("Ingeschreven");
                }
                return RedirectToAction("Index", inschrijving);
            }
            catch(Exception)
            {
                return View();
            }
        }

        [Route("/CAS_YK/CASsite/CursistInschrijven/Ingeschreven")]
        public ActionResult Ingeschreven(Inschrijving inschrijving)
        {
            return View(inschrijving);
        }
    }
}

Case1/FrontEnd/Minor.Case1.FrontEnd/src/Minor.Case1.FrontEnd.FrontEnd/Controllers/CursusInstantieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Minor.Case1.FrontEnd.FrontEnd.Agents;
using Minor.Case1.FrontEnd.FrontEnd.Agents.Models;
using Minor.Case1.FrontEnd.FrontEnd.Helpers;
using Minor.Case1.FrontEnd.FrontEnd.ViewModels;
using Microsoft.AspNetCore.Routing;

namespace Minor.Case1.FrontEnd.FrontEnd.Controllers
{
    public class CursusInstantieController : Controller
    {
        private ICursusInstantieService _agent;
        public CursusInstantieController()
        {
            _agent = new CursusInstantieService();
            _agent.BaseUri = new Uri(" http://localhost:11380/");
        }
        // GET: CursusUploaden/Details/5
        [Route("/CAS_YK/CASsite/CursusInstantie/Index")]
        public ActionResult Index(int? weekNummer, int? jaar)
        {
            int jaartal = jaar ?? DateTime.Now.Year;
            int week = weekNummer ?? DateHelper.GetWeekNummer(DateTime.Now);
            var instanties = _agent.GetCursusInstantiesVanEenBepaaldeWeek(new DateModel()
            {
                Jaar = jaartal,
                Week = week,
            });
            return View(new CursusInstantieDetailsViewModel((IEnumerable<CursusInstantie>)instanties)
            {
                Jaar = jaartal,
                WeekNummer = week,
            });
        }
        [Route("/CAS_YK/CASsite/CursusInstantie/WeekVerder")]
        public ActionResult WeekVerder(int? weekNummer, int? jaar)
        {
            weekNummer++;
            if (weekNummer >= 54)
            {
                jaar++;
                weekNummer = 1;
            }
            return RedirectToAction("Index", new RouteValueDictionary(
                new { controller = "CursusInstantie", action = "Index", weekNummer = weekNummer, jaar = jaar }));
        }

        [Route("/CAS_YK/CASsite/CursusInstantie/WeekTerug")]
        public ActionResult WeekTerug(int? weekNummer, int? jaar)
        {
            weekNummer--;
            if (weekNummer <= 0)
            {
                jaar--;
                weekNummer = 53;
            }
            return RedirectToAction("Index", new RouteValueDictionary(
                new { controller = "CursusInstantie", action = "Index", weekNummer = weekNummer, jaar = jaar }));
        }

        [Route("/CAS_YK/CASsite/CursusInstantie/Inschrijvingen")]
        public IActionResult Inschrijvingen(int id)
        {
            
            return View(new InschrijvingenViewModel()
            {
                Inschrijvingen = (IList<Inschrijving>)_agent.GetInschrijvingenByCursusInstantieId(id),
                InstantieId = id
            });
        }
    }
}

Case1/FrontEnd/Minor.Case1.FrontEnd/src/Minor.Case1.FrontEnd.FrontEnd/Views/CursusInstantie/Index.cshtml
@model Minor.Case1.FrontEnd.FrontEnd.ViewModels.CursusInstantieDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Overzicht</h2>

<form asp-action="Index"asp-controller="CursusInstantie" method="post">
    @Html.LabelFor(model => model.WeekNummer): @Html.EditorFor(model => model.WeekNummer) @Html.LabelFor(model => model.Jaar): @Html.EditorFor(model => model.Jaar)<br />
    <button type="submit" class="btn btn-default">Toon week</button>
</form>
<div style="padding-top:5px">
    <form asp-action="WeekVerder" asp-controller="CursusInstantie" method="post" style="float:right">
        @Html.HiddenFor(model => model.WeekNummer)
        @Html.HiddenFor(model => model.Jaar)
        <button type="submit" class="btn btn-default">Volgende week</button>
    </form>
    <form asp-action="WeekTerug" asp-controller="CursusInstantie" method="post">
        @Html.HiddenFor(model => model.WeekNummer)
        @Html.HiddenFor(model => model.Jaar)
        <button type="submit" class="btn btn-default">Vorige week</button>
    </form>
</div>
<table class="table">
    <thead>
        <tr>            
            <th>Startdatum</th>
            <th>Duur</th>
            <th>Cursus naam</th>
            <th>Cursuscode</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Instanties) {
        <tr>
            <td>
                @item.StartDatum
            </td>
            <td>
                @item.Cursus.Dagen dagen
            </td>
            <td>
                @item.Cursus.Titel                
            </td>
            <td>
                @item.Cursus.Code
            </td>        
            <td>                
                @Html.ActionLink("Inschrijvingen", "Inschrijvingen", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Case1/FrontEnd/Minor.Case1.FrontEnd/src/Minor.Case1.FrontEnd.FrontEnd/Views/CursusInstantie/Inschrijvingen.cshtml
@model Minor.Case1.FrontEnd.FrontEnd.ViewModels.InschrijvingenViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Overzicht van inschrijvingen</h2>
@Html.ActionLink("Inschrijven", "Index", "CursistInschrijven", new { id = Model.InstantieId })
<table class="table">
    <thead>
        <tr>            
            <th>Naam</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Inschrijvingen) {
        <tr>
            <td>
                @item.Cursist.Voornaam @item.Cursist.Achternaam
            </td>           
        </tr>
}
    </tbody>
</table>